hmcts/cmc-ccd-domain

README.md
definition/README.md
definition/bin/upload-ccd-definition-to-env.sh

https://tools.hmcts.net/jira/browse/ROC-5246
Move to new repo.
Note: tested `upload-ccd-definition-to-env.sh` script on local environment only! I can't easily test on another env but will use when updating demo.
```
```

Update readme and move upload to env script

---

definition/data/sheets/AuthorisationCaseEvent.json
definition/data/sheets/CaseEvent.json

https://tools.hmcts.net/jira/browse/ROC-5615
removing ccj upload event
```
- [ X] Yes
```

ROC-5615 removing ccj upload event

---

definition/data/sheets/AuthorisationCaseEvent.json
definition/data/sheets/CaseEvent.json

Reverting to 1.2.4 as in Excel definitions actually released. Will create new PR and bump version.
Reverts hmcts/cmc-ccd-domain#6

Revert "ROC-5615 removing ccj upload event"

---

.github/PULL_REQUEST_TEMPLATE.md
definition/bin/upload-ccd-definition-to-env.sh

The claim store url was wrong 😬 
```
```

Fix claim store url

---

.travis.yml

remove on release

---

definition/README.md

This PR updates readme  to clear minor mistakes.

Update read me

---

definition/data/sheets/CaseEventToFields.json
definition/data/sheets/ComplexTypes.json

ROC-5934: Adding scanned docs in paper response review

---

definition/data/sheets/CaseTypeTab.json

ROC-5991-scanned-document-edit

---

definition/data/sheets/CaseEventToComplexTypes.json
definition/data/sheets/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/ROC-5991
Add missing sheet
```
```

Add CaseEventToComplexTypes sheet

---

definition/data/sheets/ComplexTypes.json

receivedateTime in caseDocument

---

VERSION.yaml
azure-pipelines.yml

Release stage runs successfully but reports as failed:
```
##[error]Script failed with error: Error: /bin/bash failed with return code: 0
```
```
```

Fix release stage in Azure pipeline

---

definition/data/sheets/FixedLists.json

This PR removes the duplicate entry in fixed lists.

Remove duplicate entry

---

definition/data/sheets/AuthorisationCaseState.json

ROC-6797:Permission for all states to proceedToCaseman state

---

definition/data/sheets/FixedLists.json

https://tools.hmcts.net/jira/browse/ROC-7859
Added PAPER_RESPONSE_COUNTER_CLAIM StaffDocumentType
```
```

Added PAPER_RESPONSE_COUNTER_CLAIM StaffDocumentType (demo)

---

definition/data/sheets/FixedLists.json

https://tools.hmcts.net/jira/browse/ROC-7859
Added PAPER_RESPONSE_COUNTER_CLAIM StaffDocumentType
```
```

Added PAPER_RESPONSE_COUNTER_CLAIM StaffDocumentType (prod)

---

definition/data/sheets/State.json

https://tools.hmcts.net/jira/browse/ROC-7698
Change name and description of judgeDecideAmount state
```
```

Change name and description of judgeDecideAmount state

---

definition/data/sheets/State.json

https://tools.hmcts.net/jira/browse/ROC-7698
```
```

Feature/roc 7698/fix state description demo

---

definition/data/sheets/WorkBasketResultFields.json

https://tools.hmcts.net/jira/browse/ROC-7895
Allowing LA and caseworker to see preferred court column
```
- [x ] No
```

ROC-7895 | allowing LA and caseworkers to see preferred court

---

definition/data/sheets/AuthorisationCaseEvent.json
definition/data/sheets/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/ROC-7429
Additional pull request to removed duplicate entries introduce while resolving conflicts
```
```

Removing duplicate entires which introduced while removing conflicts

---

definition/data/sheets/AuthorisationCaseEvent.json

https://tools.hmcts.net/jira/browse/ROC-8231
Allowing cmc anonymous case worker with a role to upload claimant DQ
```
```

ROC-8231 - allowing support tools to create direction questionaire

---

definition/bin/upload-ccd-definition-to-env.sh
definition/data/sheets/AuthorisationCaseField.json
definition/data/sheets/CaseField.json
definition/data/sheets/CaseTypeTab.json

ROC-7924
Payment History tab changes
```
```

ROC-7924 Payment History Tab changes

---

definition/data/sheets/AuthorisationCaseField.json

HWF field condition

---

definition/data/sheets/AuthorisationCaseEvent.json

Revert Issue HelpWithFees Readonly events

---

definition/data/sheets/AuthorisationCaseEvent.json

ROC-8940
HwF : Remove interest recalculate event from CCD and the claim store 
```
```

ROC-8940 remove recalulate interest fees event for HWF claim

---

definition/data/sheets/AuthorisationCaseField.json

changes to allow caseworker to update field

---

definition/data/sheets/AuthorisationCaseField.json

Allow caseworker to update new preferredcourt field

---

definition/data/sheets/FixedLists.json

https://tools.hmcts.net/jira/browse/ROC-9478
Peterborough court name change
```
```

Peterborough court name change

---

definition/data/sheets/FixedLists.json

https://tools.hmcts.net/jira/browse/CIV-10929
```
```

incorrect letter type update

---

Jenkinsfile_CNP

There seems to be scripts already to upload to environments. Planning on running that in Jenkins pipeline.
```
```

Jenkins build to automate upload to env script

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/DTSCCI-33
```
```

enable ccd config import for prod and demo

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/DTSCCI-33
```
```

include ccd importer user

---

definition/data/sheets/FixedLists.json

https://tools.hmcts.net/jira/browse/DTSCCI-257
```
```

DTSCCI-257: Correct spacing in Caernarfon Justice Centre

---

definition/data/sheets/FixedLists.json

https://tools.hmcts.net/jira/browse/DTSCCI-257
```
```

DTSCCI-257: Add Small Claims Mediation Service (SCMS)

---

build.gradle

Remove bintray

---

definition/data/sheets/FixedLists.json

https://tools.hmcts.net/jira/browse/DTSCCI-257
```
```

DTSCCI-257: Add Online Civil Money Claims Service Centre
